### ISSUE TITLE
operator 'in' partition pruning cause full table scan

### ISSUE THREAD

**Issue by imtbkcat** [pingcap/tidb#16681]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
create table t1 (a int)  partition by range (a) (
    partition p0 values less than (10),
    partition p1 values less than (20),
    partition p2 values less than (30),
    partition p3 values less than (40),
    partition p4 values less than MAXVALUE
);

explain select * from t1 where a in (1, 31, 100);
```

This problem also exist for hash partition table.

### 2. What did you expect to see?

just query P0, P3, P4

### 3. What did you see instead?

```

+------------------------+----------+-----------+------------------------+--------------------------------+
| id                     | estRows  | task      | access object          | operator info                  |
+------------------------+----------+-----------+------------------------+--------------------------------+
| Union_11               | 150.00   | root      |                        |                                |
| ├─TableReader_14       | 30.00    | root      |                        | data:Selection_13              |
| │ └─Selection_13       | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
| │   └─TableFullScan_12 | 10000.00 | cop[tikv] | table:t1, partition:p0 | keep order:false, stats:pseudo |
| ├─TableReader_17       | 30.00    | root      |                        | data:Selection_16              |
| │ └─Selection_16       | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
| │   └─TableFullScan_15 | 10000.00 | cop[tikv] | table:t1, partition:p1 | keep order:false, stats:pseudo |
| ├─TableReader_20       | 30.00    | root      |                        | data:Selection_19              |
| │ └─Selection_19       | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
| │   └─TableFullScan_18 | 10000.00 | cop[tikv] | table:t1, partition:p2 | keep order:false, stats:pseudo |
| ├─TableReader_23       | 30.00    | root      |                        | data:Selection_22              |
| │ └─Selection_22       | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
| │   └─TableFullScan_21 | 10000.00 | cop[tikv] | table:t1, partition:p3 | keep order:false, stats:pseudo |
| └─TableReader_26       | 30.00    | root      |                        | data:Selection_25              |
|   └─Selection_25       | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
|     └─TableFullScan_24 | 10000.00 | cop[tikv] | table:t1, partition:p4 | keep order:false, stats:pseudo |
+------------------------+----------+-----------+------------------------+--------------------------------+
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

```
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-221-g15e961ad3
Git Commit Hash: 15e961ad379c4f98bdcef2dc6485d1ce4587e292
Git Branch: master
UTC Build Time: 2020-04-21 01:30:37
GoVersion: go1.13.9
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by zz-jason** [comment]
confirmed that it's fixed in v4.0.0:

```sql
TiDB(root@127.0.0.1:test) > explain select * from t1 where a in (1, 31, 100);
+------------------------------+----------+-----------+------------------------+--------------------------------+
| id                           | estRows  | task      | access object          | operator info                  |
+------------------------------+----------+-----------+------------------------+--------------------------------+
| Union_9                      | 90.00    | root      |                        |                                |
| ├─TableReader_12             | 30.00    | root      |                        | data:Selection_11              |
| │ └─Selection_11             | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
| │   └─TableFullScan_10       | 10000.00 | cop[tikv] | table:t1, partition:p0 | keep order:false, stats:pseudo |
| ├─TableReader_15             | 30.00    | root      |                        | data:Selection_14              |
| │ └─Selection_14             | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
| │   └─TableFullScan_13       | 10000.00 | cop[tikv] | table:t1, partition:p3 | keep order:false, stats:pseudo |
| └─TableReader_18             | 30.00    | root      |                        | data:Selection_17              |
|   └─Selection_17             | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
|     └─TableFullScan_16       | 10000.00 | cop[tikv] | table:t1, partition:p4 | keep order:false, stats:pseudo |
+------------------------------+----------+-----------+------------------------+--------------------------------+
10 rows in set (0.00 sec)
```

**Comment by lysu** [comment]
it doesn't full fixed, `partition by range columns(...)` still cannot be pruned if using `in`

```
MySQL [test]> create table t3 (a varchar(100)) partition by range columns(a) (partition p0 values less than ("1"), partition p1 values less than("3"), partition p2 values less than(5), partition p3 values less than(7));
Query OK, 0 rows affected (0.011 sec)

MySQL [test]> explain select * from t3 where a in('0', '2');
+------------------------------+----------+-----------+------------------------+--------------------------------+
| id                           | estRows  | task      | access object          | operator info                  |
+------------------------------+----------+-----------+------------------------+--------------------------------+
| PartitionUnion_10            | 80.00    | root      |                        |                                |
| ├─TableReader_13             | 20.00    | root      |                        | data:Selection_12              |
| │ └─Selection_12             | 20.00    | cop[tikv] |                        | in(test.t3.a, "0", "2")        |
| │   └─TableFullScan_11       | 10000.00 | cop[tikv] | table:t3, partition:p0 | keep order:false, stats:pseudo |
| ├─TableReader_16             | 20.00    | root      |                        | data:Selection_15              |
| │ └─Selection_15             | 20.00    | cop[tikv] |                        | in(test.t3.a, "0", "2")        |
| │   └─TableFullScan_14       | 10000.00 | cop[tikv] | table:t3, partition:p1 | keep order:false, stats:pseudo |
| ├─TableReader_19             | 20.00    | root      |                        | data:Selection_18              |
| │ └─Selection_18             | 20.00    | cop[tikv] |                        | in(test.t3.a, "0", "2")        |
| │   └─TableFullScan_17       | 10000.00 | cop[tikv] | table:t3, partition:p2 | keep order:false, stats:pseudo |
| └─TableReader_22             | 20.00    | root      |                        | data:Selection_21              |
|   └─Selection_21             | 20.00    | cop[tikv] |                        | in(test.t3.a, "0", "2")        |
|     └─TableFullScan_20       | 10000.00 | cop[tikv] | table:t3, partition:p3 | keep order:false, stats:pseudo |
+------------------------------+----------+-----------+------------------------+--------------------------------+
13 rows in set (0.002 sec)

MySQL [test]> explain select * from t3 where a in('0');
+-------------------------+----------+-----------+------------------------+--------------------------------+
| id                      | estRows  | task      | access object          | operator info                  |
+-------------------------+----------+-----------+------------------------+--------------------------------+
| TableReader_8           | 10.00    | root      |                        | data:Selection_7               |
| └─Selection_7           | 10.00    | cop[tikv] |                        | eq(test.t3.a, "0")             |
|   └─TableFullScan_6     | 10000.00 | cop[tikv] | table:t3, partition:p0 | keep order:false, stats:pseudo |
+-------------------------+----------+-----------+------------------------+--------------------------------+
3 rows in set (0.001 sec)
```

**Comment by zz-jason** [comment]
confirmed that the issue still existed:

queries to be executed:

```sql
drop table if exists t3;
create table t3 (
	a varchar(100)
) partition by range columns(a) (
	partition p0 values less than("1"),
	partition p1 values less than("3"),
	partition p2 values less than("5"),
	partition p3 values less than("7")
);
set @@tidb_partition_prune_mode='dynamic';
explain select * from t3 where a in('0', '2');
```

result of the last statement:

```sql
+-------------------------+----------+-----------+---------------+--------------------------------+
| id                      | estRows  | task      | access object | operator info                  |
+-------------------------+----------+-----------+---------------+--------------------------------+
| TableReader_7           | 20.00    | root      | partition:all | data:Selection_6               |
| └─Selection_6           | 20.00    | cop[tikv] |               | in(test.t3.a, "0", "2")        |
|   └─TableFullScan_5     | 10000.00 | cop[tikv] | table:t3      | keep order:false, stats:pseudo |
+-------------------------+----------+-----------+---------------+--------------------------------+
3 rows in set (0.00 sec)
```

TiDB version:

```sql
TiDB(root@127.0.0.1:test) > select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-2690-g91cd5bf4b-dirty
Edition: Community
Git Commit Hash: 91cd5bf4bb5aa17908a23ada16a6d6585e0e35e2
Git Branch: HEAD
UTC Build Time: 2021-04-20 19:54:26
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by qw4990** [comment]
Close since it has been solved.
```
mysql> explain select * from t1 where a in (1, 31, 100);
+------------------------------+----------+-----------+------------------------+--------------------------------+
| id                           | estRows  | task      | access object          | operator info                  |
+------------------------------+----------+-----------+------------------------+--------------------------------+
| PartitionUnion_10            | 90.00    | root      |                        |                                |
| ├─TableReader_13             | 30.00    | root      |                        | data:Selection_12              |
| │ └─Selection_12             | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
| │   └─TableFullScan_11       | 10000.00 | cop[tikv] | table:t1, partition:p0 | keep order:false, stats:pseudo |
| ├─TableReader_16             | 30.00    | root      |                        | data:Selection_15              |
| │ └─Selection_15             | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
| │   └─TableFullScan_14       | 10000.00 | cop[tikv] | table:t1, partition:p3 | keep order:false, stats:pseudo |
| └─TableReader_19             | 30.00    | root      |                        | data:Selection_18              |
|   └─Selection_18             | 30.00    | cop[tikv] |                        | in(test.t1.a, 1, 31, 100)      |
|     └─TableFullScan_17       | 10000.00 | cop[tikv] | table:t1, partition:p4 | keep order:false, stats:pseudo |
+------------------------------+----------+-----------+------------------------+--------------------------------+
10 rows in set (0.00 sec)
```
