### ISSUE TITLE
No matches for kind "TidbCluster" in version "pingcap.com/v1alpha1"

### ISSUE THREAD

**Issue by ClSlaid** [pingcap/tidb#19344]
### What version of TiKV are you using?

v4.0.4
### What operating system and CPU are you using?

kubernetes
system: Ubuntu 18.04 LTS
CPU:  AMD EPYC 7K62 48-Core Processor
Actually a one core 1 GiB virtual server.
### Steps to reproduce

When following [docs](https://docs.pingcap.com/tidb-in-kubernetes/stable/configure-a-tidb-cluster#pdtikvtidb), trying to deploy a demo Tidb Cluster on my VPS with the [.yaml file](https://github.com/pingcap/tidb-operator/blob/master/examples/tiflash/tidb-cluster.yaml)
### What did you expect?
Successfully deploy TiDB cluster demo.
### What did happened?
I stored the content in `tidb_cluster.yaml`, and tried to deploy TiDB on my VPS with Kubectl. 
```bash
kubectl apply -f tidb_cluster.yaml
```
error occured as:
```
error: unable to recognize "tidb-cluster.yaml": no matches for kind "TidbCluster" in version "pingcap.com/v1alpha1"
```
Then I looked up more detailed [link](https://github.com/pingcap/tidb-operator/blob/master/docs/api-references/docs.md), its content clearly show that "TidbCluster" is actually in version "pingcap.com/v1alpha1".
So I tried accessing pingcap.com/v1alpha1 with browser, only returning a 404 page.
Using curl to get content.
```bash
curl pingcap.com/v1alpha1 | cat
```
output:
```
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
What happend? Is this a network problem?

**Comment by lichunzhu** [comment]
Have you deployed `tidb-operator`? https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-tidb-operator

**Comment by ClSlaid** [comment]
> Have you deployed `tidb-operator`? https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-tidb-operator

Not really, I may try it later

**Comment by yahonda** [comment]
I've got a similar error yesterday and this issue has been resolved after deploying tidb-operator.

```console
% kubectl create -f ./tidb-cluster.yaml -n tidb-cluster
error: unable to recognize "./tidb-cluster.yaml": no matches for kind "TidbCluster" in version "pingcap.com/v1alpha1"
```

**Comment by hq6** [comment]
I'm still getting this error despite deploying TiDB operator:

```
kubectl get pods --namespace tidb-admin -l app.kubernetes.io/instance=tidb-operator
NAME                                      READY   STATUS    RESTARTS   AGE
tidb-controller-manager-8b6495689-kx4tg   1/1     Running   0          3m48s
tidb-scheduler-58558fc9d7-ckkrc           2/2     Running   0          3m48s

kubectl apply -f tidb-cluster.yaml -n tidb-cluster
error: unable to recognize "tidb-cluster.yaml": no matches for kind "TidbCluster" in version "pingcap.com/v1alpha1"

```
