### ISSUE TITLE
When a binlog message too large error occurs, tidb-server exits abnormally.

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#28659]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Create a very large transaction of over 2G.

### 2. What did you expect to see? (Required)
Execution failure.

### 3. What did you see instead (Required)
tidb-server exited.

```
[2021/09/27 17:17:44.432 +08:00] [WARN] [session.go:1533] ["run statement failed"] [conn=341] [schemaVersion=12389] [error="[global:3]critical error rpc error: code = ResourceExhausted desc = trying to send message larger than max (4097419655 vs. 2147483647)"] [session="{\n  \"currDBName\": \"polcent_db\",\n  \"id\": 341,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": {\n    \"Username\": \"tiuser1\",\n    \"Hostname\": \"10.79.166.195\",\n    \"CurrentUser\": false,\n    \"AuthUsername\": \"tiuser1\",\n    \"AuthHostname\": \"%\"\n  }\n}"]
[2021/09/27 17:17:44.432 +08:00] [FATAL] [conn.go:871] ["critical error, stop the server"] [conn=341] [error="[global:3]critical error rpc error: code = ResourceExhausted desc = trying to send message larger than max (4097419655 vs. 2147483647)"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:871\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:485"]
```
### 4. What is your TiDB version? (Required)
c16092ef6aff5ef67da1283cdbe21bfb7dc44b72

**Comment by jackysp** [comment]
In https://github.com/pingcap/tidb/blob/7755d25aba5120dafde98fff11ab3b98ca4d192f/sessionctx/binloginfo/binloginfo.go#L269 , it tries to catch "received message larger than max", but we got "trying to send message larger than max"

![image](https://user-images.githubusercontent.com/4352397/136536110-e8952e65-c92b-4d83-9be9-b833d271548a.png)

PTAL @coocood

**Comment by coocood** [comment]
> In
> 
> https://github.com/pingcap/tidb/blob/7755d25aba5120dafde98fff11ab3b98ca4d192f/sessionctx/binloginfo/binloginfo.go#L269
> 
> , it tries to catch "received message larger than max", but we got "trying to send message larger than max"
> ![image](https://user-images.githubusercontent.com/4352397/136536110-e8952e65-c92b-4d83-9be9-b833d271548a.png)
> 
> PTAL @coocood

So we can change it to `message larger than max'

**Comment by lichunzhu** [comment]
Should be fixed by https://github.com/pingcap/tidb-binlog/pull/1039

**Comment by lichunzhu** [comment]
close this now because https://github.com/pingcap/tidb-binlog/pull/1039 is already fixed. Feel free to reopen this if a further problem is found.

**Comment by jackysp** [comment]
The bug is still here, it happened in v6.5.3. PTAL @lichunzhu
